/// Created from: http://localhost:57772/csp/healthshare/bloodtransfusion/BloodTransfusion.BS.HISService.cls?wsdl
Class HIS.Proxy.s0.EnsRequest Extends HIS.Proxy.s0.EnsMessagebody [ ProcedureBlock ]
{

Parameter ELEMENTQUALIFIED = 1;

Parameter NAMESPACE = "http://myhospital.org";

Parameter XMLNAME = "Ens_Request";

Parameter XMLTYPE = "Ens_Request";

Storage Default
{
<Type>%Library.CacheSerialState</Type>
}

}
